name: Trello API Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  schedule:
    - cron: '0 3 * * *' # Автоматический ночной запуск каждый день в 3:00 UTC

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Клонирование репозитория
      uses: actions/checkout@v4

    - name: Установка Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Запуск автотестов Pytest
      env:
        TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
        TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
      run: |
        pytest
      continue-on-error: true

    - name: Сохранение результатов Allure в артефакты GitHub Actions
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results
        path: allure-results
        retention-days: 10

    - name: Выкачивание истории прошлых отчётов Allure
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Генерация Allure HTML отчёта
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history

    - name: Публикация отчёта в GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history